version: '3'

volumes:

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cadastro_infantil_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
    command: /start

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: cadastro_infantil_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: cadastro_infantil_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: cadastro_infantil_production_flower
    command: /start-flower

  
