# Generated by Django 3.0.5 on 2020-06-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulario', '0002_auto_20200605_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(help_text='Protocolo automatico', max_length=10, unique=True)),
                ('exportado', models.BooleanField(default=False, help_text='FLAG que esta solicitacao já foi exportada')),
                ('dre', models.CharField(blank=True, help_text='Seleciona qual DRE é responsavel', max_length=50)),
                ('dt_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('dt_modificacao', models.DateTimeField(auto_now=True)),
                ('dados', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dados', to='formulario.DadosCrianca')),
            ],
            options={
                'db_table': 'CI_solicitacao',
            },
        ),
    ]
