# Generated by Django 3.0.5 on 2020-06-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='protocolo',
            field=models.CharField(help_text='Protocolo automatico', max_length=50, unique=True),
        ),
    ]
