# Generated by Django 3.0.5 on 2020-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_auto_20200605_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='distrito',
            field=models.CharField(blank=True, help_text='Seleciona o distrito dessa solicitacao', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='dre',
            field=models.CharField(blank=True, choices=[('JT', 'JT - JACANA-TREMEBE'), ('SA', 'SA - SANTO AMARO'), ('PE', 'PE - PENHA'), ('IQ', 'IQ - ITAQUERA'), ('IP', 'IP - IPIRANGA'), ('BT', 'BT - BUTANTA'), ('SM', 'SM - SAO MATEUS'), ('CS', 'CS - CAPELA DO SOCORRO'), ('MP', 'MP - SAO MIGUEL'), ('CL', 'CL - CAMPO LIMPO'), ('FB', 'FB - FREGUESIA-BRASILANDIA'), ('NÃO ENCONTRADO', 'NÃO ENCONTRADO')], help_text='Seleciona qual DRE é responsavel', max_length=50),
        ),
    ]
