# Generated by Django 3.0.5 on 2020-06-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_auto_20200609_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='dre',
            field=models.CharField(blank=True, choices=[('BT', 'BT - BUTANTA'), ('CL', 'CL - CAMPO LIMPO'), ('CS', 'CS - CAPELA DO SOCORRO'), ('FB', 'FB - FREGUESIA-BRASILANDIA'), ('G', 'G - GUAIANASES'), ('IP', 'IP - IPIRANGA'), ('IQ', 'IQ - ITAQUERA'), ('JT', 'JT - JACANA-TREMEBE'), ('MP', 'MP - SAO MIGUEL'), ('PE', 'PE - PENHA'), ('PJ', 'PJ - PIRITUBA-JARAGUA'), ('SA', 'SA - SANTO AMARO'), ('SM', 'SM - SAO MATEUS'), ('NÃO ENCONTRADO', 'NÃO ENCONTRADO')], help_text='Seleciona qual DRE é responsavel', max_length=50),
        ),
    ]
