# Generated by Django 3.0.5 on 2022-01-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_auto_20200623_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='agrupamento',
            field=models.CharField(blank=True, choices=[('BERCARIO I', 'BERCARIO I'), ('BERCARIO II', 'BERCARIO II'), ('MINI GRUPO I', 'MINI GRUPO I'), ('MINI GRUPO II', 'MINI GRUPO II'), ('INFANTIL', 'INFANTIL'), ('INFANTIL I', 'INFANTIL I'), ('INFANTIL II', 'INFANTIL II'), ('INFANTIL II', 'INFANTIL II'), ('SEM AGRUPAMENTO', 'SEM AGRUPAMENTO')], max_length=50),
        ),
    ]
