# Generated by Django 3.0.5 on 2020-06-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCrianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_crianca', models.CharField(help_text='Nome da criança', max_length=255)),
                ('sexo_crianca', models.CharField(help_text='Sexo da criança (M/F)', max_length=1)),
                ('dt_nasc_crianca', models.DateField(help_text='Data de nascimento da criança')),
                ('cep_moradia', models.CharField(help_text='CEP da crianca (00000000)', max_length=8)),
                ('endereco_moradia', models.CharField(help_text='Endereço da criança sem numero', max_length=255)),
                ('numero_moradia', models.CharField(help_text='Numero do endereço', max_length=20)),
                ('complemento_moradia', models.CharField(blank=True, help_text='Complemento do endereço', max_length=20)),
                ('nome_mae', models.CharField(help_text='Nome da mãe da criança', max_length=255)),
                ('nome_pai', models.CharField(blank=True, help_text='Nome do pai da criança', max_length=255)),
                ('tipo_responsavel', models.CharField(help_text='Tipo de responsavel da crianca', max_length=1)),
                ('nome_responsavel', models.CharField(blank=True, help_text='Nome do responsavel da criança', max_length=255)),
                ('cpf_responsavel', models.CharField(help_text='CPF do responsavel', max_length=11)),
                ('dt_nasc_responsavel', models.DateField(help_text='Data de nascimento do responsavel')),
                ('email_responsavel', models.EmailField(help_text='Email do responsavel', max_length=254)),
                ('certidao_crianca', models.ImageField(help_text='Foto da certidão de nascimento em BASE64', upload_to='')),
            ],
            options={
                'db_table': 'dados_crianca',
            },
        ),
    ]
