# Generated by Django 3.0.5 on 2020-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosCrianca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_crianca', models.CharField(help_text='Nome da criança', max_length=255)),
                ('sexo_crianca', models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], help_text='Sexo da criança (M/F)', max_length=1)),
                ('nacionalidade_crianca', models.CharField(help_text='Nacionalidade da criança', max_length=100)),
                ('dt_entrada_brasil', models.DateField(blank=True, help_text='Caso estrangeiro, quando entrou no Brasil', null=True)),
                ('dt_nasc_crianca', models.DateField(help_text='Data de nascimento da criança')),
                ('uf_nasc_crianca', models.CharField(blank=True, help_text='UF de Nascimento da Criança', max_length=20)),
                ('municipio_nasc_crianca', models.CharField(blank=True, help_text='Municipio de Nascimento da Criança', max_length=100)),
                ('raca_cor_crianca', models.CharField(choices=[(1, 'AMARELA'), (2, 'BRANCA'), (3, 'INDIGENA'), (4, 'PARDA'), (5, 'PRETA'), (6, 'NAO DECLARADA')], max_length=1)),
                ('tem_nee', models.BooleanField(default=False, help_text='Crianca portadora de Necessidades Especiais?')),
                ('tipo_nee', models.CharField(blank=True, help_text='Qual necessidade especial', max_length=255)),
                ('filiacao1_nome', models.CharField(help_text='Nome da Filiacao I (Pref. Mãe)', max_length=100)),
                ('filiacao1_falecido', models.BooleanField(default=False, help_text='Filiação I é falecido')),
                ('filiacao1_sexo', models.CharField(choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], help_text='Sexo da filiacao I (M/F)', max_length=1)),
                ('filiacao1_nacionalidade', models.CharField(help_text='Nacionalidade da filiacao I', max_length=100)),
                ('filiacao2_consta', models.BooleanField(default=True, help_text='Filiacao II está na certidão da crianca?')),
                ('filiacao2_nome', models.CharField(blank=True, help_text='Nome da Filiacao II (Pref. Mãe)', max_length=100)),
                ('filiacao2_falecido', models.BooleanField(default=False, help_text='Filiação II é falecido')),
                ('filiacao2_sexo', models.CharField(blank=True, choices=[('F', 'FEMININO'), ('M', 'MASCULINO')], help_text='Sexo da filiacao II (M/F)', max_length=1)),
                ('filiacao2_nacionalidade', models.CharField(blank=True, help_text='Nacionalidade da filiacao II', max_length=100)),
                ('cep_moradia', models.CharField(help_text='CEP da crianca (00000000)', max_length=8)),
                ('endereco_moradia', models.CharField(help_text='Endereço da criança sem numero', max_length=255)),
                ('numero_moradia', models.CharField(help_text='Numero do endereço', max_length=20)),
                ('complemento_moradia', models.CharField(blank=True, help_text='Complemento do endereço', max_length=20)),
                ('tipo_responsavel', models.CharField(help_text='Tipo de responsavel da crianca', max_length=1)),
                ('nome_responsavel', models.CharField(blank=True, help_text='Nome do responsavel da criança', max_length=255)),
                ('cpf_responsavel', models.CharField(help_text='CPF do responsavel', max_length=11)),
                ('dt_nasc_responsavel', models.DateField(help_text='Data de nascimento do responsavel')),
                ('email_responsavel', models.EmailField(help_text='Email do responsavel', max_length=254)),
                ('telefone_responsavel', models.CharField(help_text='Telefone do responsavel', max_length=14)),
                ('certidao_crianca', models.ImageField(help_text='Foto da certidão de nascimento em BASE64', upload_to='')),
            ],
            options={
                'db_table': 'CI_dados_crianca',
            },
        ),
    ]
