# Generated by Django 3.0.5 on 2020-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_auto_20200605_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscrianca',
            name='parentesco_responsavel',
            field=models.CharField(blank=True, help_text='Grau de parentesco', max_length=50),
        ),
    ]
