# Generated by Django 3.0.5 on 2020-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_dadoscrianca_telefone_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscrianca',
            name='email_responsavel',
            field=models.EmailField(blank=True, help_text='Email do responsavel', max_length=254),
        ),
    ]
