# Generated by Django 3.0.5 on 2020-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_auto_20200608_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscrianca',
            name='irmao_na_rede',
            field=models.CharField(blank=True, help_text='Criança tem irmao matriculado na rede municipal', max_length=2),
        ),
        migrations.AddField(
            model_name='dadoscrianca',
            name='nome_irmao',
            field=models.CharField(blank=True, help_text='Nome do irmão', max_length=255),
        ),
    ]
