# Generated by Django 3.0.5 on 2021-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_dadoscrianca_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscrianca',
            name='atualizacao_cadastral',
            field=models.CharField(blank=True, help_text='atualização Cadastral', max_length=3, null=True),
        ),
    ]
