# Generated by Django 3.0.5 on 2022-12-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_dadoscrianca_atualizacao_cadastral'),
    ]

    operations = [
        migrations.CreateModel(
            name='InativacaoFormulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(help_text='Data de inicio da inativação')),
                ('data_fim', models.DateField(help_text='Data de encerramento da inativação')),
                ('texto_a_ser_visualizado', models.TextField(help_text='Texto a ser exibido na inativação do site')),
            ],
            options={
                'verbose_name': 'Inativação do Formulário',
                'verbose_name_plural': 'Inativações de formulários',
            },
        ),
    ]
