# Generated by Django 3.0.5 on 2022-12-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_inativacaoformulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inativacaoformulario',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
    ]
