# Generated by Django 3.0.5 on 2022-12-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_inativacaoformulario_alterado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inativacaoformulario',
            name='data_fim',
            field=models.DateField(help_text='Último dia de inativação', verbose_name='Data Inativação ATÉ'),
        ),
        migrations.AlterField(
            model_name='inativacaoformulario',
            name='data_inicio',
            field=models.DateField(help_text='Data de inicio da inativação', verbose_name='Data Inativação DE'),
        ),
    ]
